# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a data set which contains information World cup matches. Let's use the pandas commands learned in the previous lecture to learn more about our data!

## Objectives
You will be able to:
* Understand and explain some key Pandas methods
* Access DataFrame data by using the label
* Perform boolean indexing on both Series and DataFrames
* Use simple selectors for series
* Set new Series and DataFrame inputs

## Load the data

Load the file `WorldCupMatches.csv` as a dataframe in Pandas

In [1]:
import pandas as pd
df = pd.read_csv('WorldCupMatches.csv')
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

## Common methods and attributes

Use the correct method to look at the first 7 rows of the data set.

In [2]:
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Look at the last 3 rows of the data set.

In [3]:
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of your data using `.info()`

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [5]:
(len(df), len(df.columns))

(852, 20)

Use the appropriate attribute to get the column names

In [6]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting dataframe information

When looking at the dataframe's `.head()`, you might have noticed that the games are structured chronologically in the dataframe.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [7]:
df.iloc[2:5]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

Now, print all the info from game 5-9, but we're only interested to print out the "Home Team Name" and the "Away Team Name",

In [8]:
df.loc[4:8, ['Home Team Name', 'Away Team Name']]

  Home Team Name Away Team Name
4      Argentina         France
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [9]:
df[(df.Stage == 'Group 2') & (df.Year == 1950)]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
54,1950,25 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,England,2,0,Chile,,29703.0,1,0,VAN DER MEER Karel (NED),GARDELLI Mario (BRA),DAHLNER Gunnar (SWE),208,1192,ENG,CHI
55,1950,25 Jun 1950 - 15:00,Group 2,Durival de Brito,Curitiba,Spain,3,1,USA,,9511.0,0,1,VIANA Mario (BRA),DA COSTA VIEIRA Jose (POR),DE LA SALLE Charles (FRA),208,1208,ESP,USA
60,1950,29 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,2,0,Chile,,19790.0,2,0,MALCHER Alberto (BRA),MARINO Esteban (URU),ALVAREZ Alfredo (BOL),208,1193,ESP,CHI
62,1950,29 Jun 1950 - 15:00,Group 2,Independencia,Belo Horizonte,USA,1,0,England,,10151.0,1,0,DATTILO Generoso (ITA),DE LA SALLE Charles (FRA),GALEATI Giovanni (ITA),208,1202,USA,ENG
64,1950,02 Jul 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,1,0,England,,74462.0,0,0,GALEATI Giovanni (ITA),LUTZ Jean (SUI),DATTILO Generoso (ITA),208,1199,ESP,ENG
68,1950,02 Jul 1950 - 15:00,Group 2,Ilha do Retiro,Recife,Chile,5,2,USA,,8501.0,2,0,GARDELLI Mario (BRA),HEYEN Mario Ruben (PAR),ALVAREZ Alfredo (BOL),208,1194,CHI,USA

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [10]:
df[(df.Stage == 'Group 2') & (df.Year == 1950)].loc[:, ['Attendance']]

    Attendance
54     29703.0
55      9511.0
60     19790.0
62     10151.0
64     74462.0
68      8501.0

Throughout the entire history of the world cup, How many Home games were played by the Netherlands?

In [11]:
home = len(df[df['Home Team Name'] == 'Netherlands'])

How many games were played by the Netherlands in total?

In [12]:
away = len(df[df['Away Team Name'] == 'Netherlands'])
home+away

54

Next, let's try and figure out how many games the USA played in the 2014 world cup.

In [13]:
all_games = df[(df.Year == 2014) & ((df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA'))]
len(all_games)
# away = df[df['Away Team Name'] == 'USA' & df['Year'] == 2014]
# len(home)+len(away)

5

Now, let's try to find out how many countries participated in the 1986 world cup.

Hint 1: as a first step, create a new data set that only contain games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [26]:
home_teams = df[df.Year == 1986].loc[:, 'Home Team Name'].append(df[df.Year == 1986].loc[:, 'Away Team Name'])
len(home_teams.unique())

24

In the world cup history, how matches had more than 5 goals in total?

In [31]:
len(df[(df['Home Team Goals']) + (df['Away Team Goals']) > 5])

74

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column "Half-time Goals".

In [39]:
df['Half-time Goals'] = None
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Half-time Goals
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,...,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,None
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,...,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL,None
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,...,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA,None
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,...,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER,None
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,...,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA,None

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [40]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [45]:
df = df.replace(to_replace = {'Home Team Name': {'Korea Republic': 'Korea', 'Korea DPR': 'Korea'}, 
                              'Away Team Name': {'Korea Republic': 'Korea', 'Korea DPR': 'Korea'},
                              'Home Team Initials': {'KOR': 'NSK', 'PRK': 'NSK'},
                              'Away Team Initials': {'KOR': 'NSK', 'PRK': 'NSK'}})

df[df['Home Team Name'] == "Korea"]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Half-time Goals
179,1966,15 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,1,Chile,,...,0,1,KANDIL Aly Hussein (EGY),CRAWFORD William (SCO),FINNEY Jim (ENG),238,1609,NSK,CHI,None
187,1966,19 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,0,Italy,,...,1,0,SCHWINTE Pierre (FRA),ADAIR John (NIR),TAYLOR John (ENG),238,1679,NSK,ITA,None
374,1986,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1,1,Bulgaria,,...,0,1,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308,460,NSK,BUL,None
386,1986,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2,3,Italy,,...,0,1,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308,643,NSK,ITA,None
434,1990,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1,3,Spain,,...,1,1,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322,175,NSK,ESP,None
444,1990,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0,1,Uruguay,,...,0,0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322,290,NSK,URU,None
480,1994,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0,0,Bolivia,,...,0,0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337,3065,NSK,BOL,None
524,1998,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1,3,Mexico,,...,1,0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014,8732,NSK,MEX,None
593,2002,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2,0,Poland,,...,1,0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100,43950014,NSK,POL,None
609,2002,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1,1,USA,,...,0,1,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100,43950030,NSK,USA,None
635,2002,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2,1,Italy,Win on Golden Goal,...,0,0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200,43950056,NSK,ITA,None
642,2002,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2,3,Turkey,,...,1,3,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500,43950063,NSK,TUR,None
655,2006,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2,1,Togo,,...,0,1,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100,97410014,NSK,TOG,None
710,2010,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2,0,Greece,,...,1,0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722,300061459,NSK,GRE,None
753,2010,25 Jun 2010 - 16:00,Group G,Mbombela Stadium,Nelspruit,Korea,0,3,C�te d'Ivoire,,...,0,2,Alberto UNDIANO MALLENCO (ESP),MARTINEZ Fermin (ESP),YUSTE Juan (ESP),249722,300061486,NSK,CIV,None
802,2014,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2,4,Algeria,,...,0,3,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931,300186495,NSK,ALG,None
818,2014,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0,1,Belgium,,...,0,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931,300186480,NSK,BEL,None

Make sure to verify your answer!

## Summary

In this lab, you learned how to access data within Pandas!